// @flow

import color from 'color';

import { Platform, Dimensions, PixelRatio } from 'react-native';

const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;
const platform = 'android'; // Hard Coding Android Theme IMP
const platformStyle = undefined;
const isIphoneX =
  platform === 'ios' &&
  (deviceHeight === 812 || deviceWidth === 812 || deviceHeight === 896 || deviceWidth === 896);

export default {
  platformStyle: 'material',
  platform,
  androidRipple: true,
  androidRippleColor: 'rgba(256, 256, 256, 0.3)',
  androidRippleColorDark: 'rgba(0, 0, 0, 0.15)',
  btnUppercaseAndroidText: true,
  badgeBg: 'rgba(49,29,63,1)',
  badgeColor: '#fff',
  badgePadding: 3,
  btnFontFamily: 'System',
  btnDisabledBg: 'rgba(225,125,140,1)',
  buttonPadding: 6,
  btnPrimaryBg: 'rgba(226,62,87,1)',
  btnPrimaryColor: '#fff',
  btnInfoBg: 'rgba(136,48,78,1)',
  btnInfoColor: '#fff',
  btnSuccessBg: 'rgba(49,29,63,1)',
  btnSuccessColor: '#fff',
  btnDangerBg: 'rgba(82,37,70,1)',
  btnDangerColor: '#fff',
  btnWarningBg: '#f0ad4e',
  btnWarningColor: '#fff',
  btnTextSize: 16.5,
  btnTextSizeLarge: 22.5,
  btnTextSizeSmall: 12,
  borderRadiusLarge: 57,
  iconSizeLarge: 45,
  iconSizeSmall: 18,
  cardDefaultBg: '#fff',
  cardBorderColor: '#ccc',
  CheckboxRadius: 0,
  CheckboxBorderWidth: 2,
  CheckboxPaddingLeft: 2,
  CheckboxPaddingBottom: 0,
  CheckboxIconSize: 18,
  CheckboxFontSize: 21,
  DefaultFontSize: 17,
  checkboxBgColor: 'rgba(226,62,87,1)',
  checkboxSize: 20,
  checkboxTickColor: '#fff',
  brandPrimary: '#3F51B5',
  brandInfo: '#3F57D3',
  brandSuccess: '#5cb85c',
  brandDanger: '#d9534f',
  brandWarning: '#f0ad4e',
  brandDark: '#000',
  brandLight: '#f4f4f4',
  fontFamily: 'System',
  fontSizeBase: 15,
  fontSizeH1: 27,
  fontSizeH2: 24,
  fontSizeH3: 21,
  footerHeight: 55,
  footerDefaultBg: 'rgba(255,255,255,1)',
  footerPaddingBottom: 0,
  tabBarTextColor: 'rgba(49,29,63,1)',
  tabBarTextSize: 14,
  activeTab: '#fff',
  sTabBarActiveTextColor: '#007aff',
  tabBarActiveTextColor: 'rgba(226,62,87,1)',
  tabActiveBgColor: 'rgba(255,255,255,1)',
  toolbarBtnColor: 'rgba(49,29,63,1)',
  toolbarDefaultBg: 'rgba(255,255,255,1)',
  toolbarHeight: 64,
  toolbarSearchIconSize: 20,
  toolbarInputColor: '#fff',
  searchBarHeight: 30,
  searchBarInputHeight: 30,
  toolbarBtnTextColor: '#fff',
  toolbarDefaultBorder: 'rgba(255,255,255,1)',
  iosStatusbar: 'dark-content',
  statusBarColor: 'rgba(255,255,255,1)',
  darkenHeader: '#F0F0F0',
  iconFamily: null,
  iconFontSize: 30,
  iconHeaderSize: 29,
  inputFontSize: 17,
  inputBorderColor: 'rgba(49,29,63,1)',
  inputSuccessBorderColor: '#2b8339',
  inputErrorBorderColor: '#ed2f2f',
  inputHeightBase: 50,
  inputColor: 'rgba(49,29,63,1)',
  inputColorPlaceholder: '#575757',
  btnLineHeight: 19,
  lineHeightH1: 32,
  lineHeightH2: 27,
  lineHeightH3: 22,
  lineHeight: 20,
  listBg: '#FFF',
  listBorderColor: '#c9c9c9',
  listDividerBg: '#f4f4f4',
  listBtnUnderlayColor: '#DDD',
  listItemPadding: 10,
  listNoteColor: '#808080',
  listNoteSize: 13,
  defaultProgressColor: '#E4202D',
  inverseProgressColor: '#1A191B',
  radioBtnSize: 25,
  radioSelectedColorAndroid: '#5067FF',
  radioBtnLineHeight: 29,
  segmentBackgroundColor: '#3F51B5',
  segmentActiveBackgroundColor: '#fff',
  segmentTextColor: '#fff',
  segmentActiveTextColor: '#3F51B5',
  segmentBorderColor: '#fff',
  segmentBorderColorMain: '#3F51B5',
  defaultSpinnerColor: 'rgba(226,62,87,1)',
  inverseSpinnerColor: '#1A191B',
  tabDefaultBg: 'rgba(226,62,87,1)',
  topTabBarTextColor: 'rgba(255,255,255,1)',
  topTabBarActiveTextColor: '#fff',
  topTabBarBorderColor: '#fff',
  topTabBarActiveBorderColor: '#fff',
  tabBgColor: '#F8F8F8',
  tabFontSize: 15,
  textColor: 'rgba(49,29,63,1)',
  inverseTextColor: '#fff',
  noteFontSize: 14,
  defaultTextColor: '#000',
  titleFontfamily: 'System',
  titleFontSize: 19,
  subTitleFontSize: 14,
  subtitleColor: 'rgba(49,29,63,1)',
  titleFontColor: 'rgba(49,29,63,1)',
  borderRadiusBase: 2,
  borderWidth: 1,
  contentPadding: 10,
  dropdownLinkColor: '#414142',
  inputLineHeight: 24,
  deviceWidth: 1440,
  deviceHeight: 798,
  isIphoneX: false,
  inputGroupRoundedBorderRadius: 30,
};
