# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Sinful' do
  pod 'GooglePlaces', '~> 3.0.3'
  pod 'GooglePlacePicker', '~> 3.0.3'
  pod 'GoogleMaps', '~> 3.0.3'
end
